-- ============================================================================
-- NANUCLOUD FISCAL SUITE - REDUNDANT DAILY DATABASE BACKUP DUMP
-- Backup ID:       backup_20260922_204823_c6iq
-- Timestamp (UTC):  2026-09-22T20:48:23.099Z
-- Database Source: neondb (PostgreSQL / Neon Cloud)
-- Integrity:       SHA-256 Checksum Verified
-- ============================================================================

BEGIN;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- ----------------------------------------------------------------------------
-- PLANS TABLE DUMP
-- ----------------------------------------------------------------------------
INSERT INTO plans (id, name, description, price_kz, queries_count, queries_included, validity_days, unit_price_kz, min_price_kz, badge, features, unlocks_import, unlocks_batch, unlocks_api, is_custom, is_popular, is_active, sort_order, created_at, updated_at) VALUES ('plan_bronze', 'Plano Bronze', 'Ideal para pequenos comerciantes e profissionais liberais.', '500.00', 10, 10, 30, '50.00', '500.00', 'Arranque', '["10 Consultas Comerciais", "Cálculo de IVA e Margens", "Simulação de Retenção na Fonte", "Exportação Básica PDF"]', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 1, '"2026-09-21T22:36:52.060Z"', '"2026-09-21T22:36:52.060Z"') ON CONFLICT (id) DO UPDATE SET updated_at = NOW();
INSERT INTO plans (id, name, description, price_kz, queries_count, queries_included, validity_days, unit_price_kz, min_price_kz, badge, features, unlocks_import, unlocks_batch, unlocks_api, is_custom, is_popular, is_active, sort_order, created_at, updated_at) VALUES ('plan_silver', 'Plano Prata', 'Para pequenos negócios com fluxo regular de cotações diárias.', '1500.00', 30, 30, 30, '50.00', '1500.00', 'Recomendado', '["30 Consultas Comerciais", "Cálculo de Lucro Líquido Real", "Simulação de Prestação de Serviços", "Suporte WhatsApp Prioritário"]', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 2, '"2026-09-21T22:36:52.060Z"', '"2026-09-21T22:36:52.060Z"') ON CONFLICT (id) DO UPDATE SET updated_at = NOW();
INSERT INTO plans (id, name, description, price_kz, queries_count, queries_included, validity_days, unit_price_kz, min_price_kz, badge, features, unlocks_import, unlocks_batch, unlocks_api, is_custom, is_popular, is_active, sort_order, created_at, updated_at) VALUES ('plan_gold', 'Plano Ouro Pro', 'Inclui Módulo Completo de Importação Aduaneira e Despacho.', '3000.00', 60, 60, 30, '50.00', '3000.00', 'Mais Popular', '["60 Consultas Globais", "Módulo de Importação Aduaneira CIF/FOB", "Pauta Aduaneira Completa", "Simulação de Intermediação & Corretagem"]', TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, 3, '"2026-09-21T22:36:52.060Z"', '"2026-09-21T22:36:52.060Z"') ON CONFLICT (id) DO UPDATE SET updated_at = NOW();
INSERT INTO plans (id, name, description, price_kz, queries_count, queries_included, validity_days, unit_price_kz, min_price_kz, badge, features, unlocks_import, unlocks_batch, unlocks_api, is_custom, is_popular, is_active, sort_order, created_at, updated_at) VALUES ('plan_platinum', 'Plano Platina Business', 'Solução completa para empresas com cálculo massivo em lote.', '5000.00', 100, 100, 30, '50.00', '5000.00', 'Empresas', '["100 Consultas Avançadas", "Operações em Lote (Excel até 1000 linhas)", "Simulação Multimodal (Marítimo, Terrestre, Aéreo)", "Desbloqueio de Todos os Módulos"]', TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, 4, '"2026-09-21T22:36:52.060Z"', '"2026-09-21T22:36:52.060Z"') ON CONFLICT (id) DO UPDATE SET updated_at = NOW();
INSERT INTO plans (id, name, description, price_kz, queries_count, queries_included, validity_days, unit_price_kz, min_price_kz, badge, features, unlocks_import, unlocks_batch, unlocks_api, is_custom, is_popular, is_active, sort_order, created_at, updated_at) VALUES ('plan_diamond', 'Plano Diamante Enterprise', 'Consultoria e volume para grandes organizações e transitários.', '10000.00', 200, 200, 30, '50.00', '10000.00', 'VIP Total', '["200 Consultas VIP", "API REST para Integração ERP", "Atendimento Prioritário por Super Administrador", "Acesso Total Irrestrito"]', TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, 5, '"2026-09-21T22:36:52.060Z"', '"2026-09-21T22:36:52.060Z"') ON CONFLICT (id) DO UPDATE SET updated_at = NOW();

-- ----------------------------------------------------------------------------
-- USERS TABLE DUMP
-- ----------------------------------------------------------------------------
INSERT INTO users (id, name, company, nif, email, phone, address, country, password_hash, role, client_category, department, permission_group_id, custom_permissions, is_active, queries_remaining, total_queries_used, active_plan_id, active_plan_name, plan_expires_at, is_import_unlocked, is_batch_unlocked, is_api_unlocked, two_factor_enabled, two_factor_phone, login_sms_enabled, birth_date, assigned_manager_id, assigned_manager_name, commercial_notes, last_daily_credit_date, phone_verified, email_verified, preferred_theme, preferred_lang, created_at, updated_at, last_login_at) VALUES ('usr_admin_nanucloud', 'Super Administrador NANUCLOUD', 'NANUCLOUD TECNOLOGIA LDA', '5001294819', 'admin@nanucloud.com', '+244 954 269 353', 'Edifício Kilamba, Luanda, Angola', 'Angola', '$2b$10$35vW5MHk.pDR5uOEXLGhDe8QD2JGoa9riROP6duFZsl.uNV0k36CG', 'super_admin', 'comercio', 'Direção Geral & Finanças', 'grp_superadmin', NULL, TRUE, 999999, 0, NULL, NULL, NULL, TRUE, TRUE, TRUE, FALSE, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, TRUE, TRUE, 'dark', 'pt', '"2026-09-21T22:36:52.060Z"', '"2026-09-21T22:36:52.060Z"', NULL) ON CONFLICT (id) DO UPDATE SET updated_at = NOW();
INSERT INTO users (id, name, company, nif, email, phone, address, country, password_hash, role, client_category, department, permission_group_id, custom_permissions, is_active, queries_remaining, total_queries_used, active_plan_id, active_plan_name, plan_expires_at, is_import_unlocked, is_batch_unlocked, is_api_unlocked, two_factor_enabled, two_factor_phone, login_sms_enabled, birth_date, assigned_manager_id, assigned_manager_name, commercial_notes, last_daily_credit_date, phone_verified, email_verified, preferred_theme, preferred_lang, created_at, updated_at, last_login_at) VALUES ('cli_001', 'António Gaspar Ferreira', 'Ferreira & Filhos Comércio Geral Lda', '5412093847', 'comercial@ferreirafilhos.ao', '+244 923 456 789', 'Av. 4 de Fevereiro, Marginal de Luanda', 'Angola', '$2b$10$5EABwXnSn3xDu1rs4TLLqew7L1E28Fs6XSrJdXleMKnXAgXOORd8y', 'client', 'comercio', NULL, NULL, NULL, TRUE, 184, 116, 'plan_gold', 'Plano Ouro Pro', NULL, TRUE, TRUE, FALSE, FALSE, NULL, FALSE, NULL, NULL, 'Super Administrador NANUCLOUD', NULL, NULL, TRUE, TRUE, 'dark', 'pt', '"2026-09-21T22:36:52.060Z"', '"2026-09-21T22:36:52.060Z"', NULL) ON CONFLICT (id) DO UPDATE SET updated_at = NOW();
INSERT INTO users (id, name, company, nif, email, phone, address, country, password_hash, role, client_category, department, permission_group_id, custom_permissions, is_active, queries_remaining, total_queries_used, active_plan_id, active_plan_name, plan_expires_at, is_import_unlocked, is_batch_unlocked, is_api_unlocked, two_factor_enabled, two_factor_phone, login_sms_enabled, birth_date, assigned_manager_id, assigned_manager_name, commercial_notes, last_daily_credit_date, phone_verified, email_verified, preferred_theme, preferred_lang, created_at, updated_at, last_login_at) VALUES ('cli_002', 'Dra. Maria Eunice Santos', 'Santos & Associados Consultoria', '5409281742', 'maria.santos@santosconsultoria.co.ao', '+244 945 112 233', 'Talatona Park, Luanda Sul', 'Angola', '$2b$10$5EABwXnSn3xDu1rs4TLLqew7L1E28Fs6XSrJdXleMKnXAgXOORd8y', 'client', 'servicos', NULL, NULL, NULL, TRUE, 742, 258, 'plan_diamond', 'Plano Diamante Enterprise', NULL, TRUE, TRUE, TRUE, FALSE, NULL, FALSE, NULL, NULL, 'Super Administrador NANUCLOUD', NULL, NULL, TRUE, TRUE, 'dark', 'pt', '"2026-09-21T22:36:52.060Z"', '"2026-09-21T22:36:52.060Z"', NULL) ON CONFLICT (id) DO UPDATE SET updated_at = NOW();
INSERT INTO users (id, name, company, nif, email, phone, address, country, password_hash, role, client_category, department, permission_group_id, custom_permissions, is_active, queries_remaining, total_queries_used, active_plan_id, active_plan_name, plan_expires_at, is_import_unlocked, is_batch_unlocked, is_api_unlocked, two_factor_enabled, two_factor_phone, login_sms_enabled, birth_date, assigned_manager_id, assigned_manager_name, commercial_notes, last_daily_credit_date, phone_verified, email_verified, preferred_theme, preferred_lang, created_at, updated_at, last_login_at) VALUES ('cli_003', 'Eng. Carlos Alberto Mendes', 'Mendes Import & Export Transitários', '5418829103', 'carlos.mendes@mendesimport.ao', '+244 912 887 766', 'Porto de Luanda, Terminal Cargas', 'Angola', '$2b$10$5EABwXnSn3xDu1rs4TLLqew7L1E28Fs6XSrJdXleMKnXAgXOORd8y', 'client', 'importacao', NULL, NULL, NULL, TRUE, 45, 255, 'plan_gold', 'Plano Ouro Pro', NULL, TRUE, TRUE, FALSE, FALSE, NULL, FALSE, NULL, NULL, 'Super Administrador NANUCLOUD', NULL, NULL, TRUE, TRUE, 'dark', 'pt', '"2026-09-21T22:36:52.060Z"', '"2026-09-21T22:36:52.060Z"', NULL) ON CONFLICT (id) DO UPDATE SET updated_at = NOW();
INSERT INTO users (id, name, company, nif, email, phone, address, country, password_hash, role, client_category, department, permission_group_id, custom_permissions, is_active, queries_remaining, total_queries_used, active_plan_id, active_plan_name, plan_expires_at, is_import_unlocked, is_batch_unlocked, is_api_unlocked, two_factor_enabled, two_factor_phone, login_sms_enabled, birth_date, assigned_manager_id, assigned_manager_name, commercial_notes, last_daily_credit_date, phone_verified, email_verified, preferred_theme, preferred_lang, created_at, updated_at, last_login_at) VALUES ('cli_004', 'Teresa Cristina Neto', 'Boutique & Cosméticos Luanda', '5420194831', 'loja@boutiqueluanda.com', '+244 933 654 321', 'Rua Rainha Ginga, Baixa de Luanda', 'Angola', '$2b$10$5EABwXnSn3xDu1rs4TLLqew7L1E28Fs6XSrJdXleMKnXAgXOORd8y', 'client', 'comercio', NULL, NULL, NULL, TRUE, 8, 42, 'plan_bronze', 'Plano Bronze', NULL, FALSE, FALSE, FALSE, FALSE, NULL, FALSE, NULL, NULL, 'Super Administrador NANUCLOUD', NULL, NULL, TRUE, TRUE, 'dark', 'pt', '"2026-09-21T22:36:52.060Z"', '"2026-09-21T22:36:52.060Z"', NULL) ON CONFLICT (id) DO UPDATE SET updated_at = NOW();

-- ----------------------------------------------------------------------------
-- SIMULATIONS TABLE DUMP
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- TRANSACTIONS TABLE DUMP
-- ----------------------------------------------------------------------------
INSERT INTO transactions (id, user_id, user_name, user_email, company_name, nif, plan_id, plan_name, amount_kz, currency, queries_granted, validity_days, payment_method, payment_reference, emis_reference, emis_terminal, payment_proof_name, payment_proof_url, payment_proof_size, gateway_fee_kz, net_amount_kz, notes, status, rejection_reason, reviewed_by_admin_id, reviewed_by_admin_name, reviewed_at, approved_at, created_at, updated_at) VALUES ('tx_pay_001', 'cli_001', 'António Gaspar Ferreira', 'comercial@ferreirafilhos.ao', 'Ferreira & Filhos Comércio Geral Lda', '5412093847', 'plan_gold', 'Plano Ouro Pro (60 Consultas)', '3000.00', 'AOA', 60, 30, 'bank_transfer', 'BAI-COMP-2026-9921', NULL, NULL, 'Comprovativo_BAI_3000Kz.pdf', NULL, NULL, '0.00', '0.00', 'Transferência efetuada via BAI Directo para a conta NANUCLOUD.', 'pending', NULL, NULL, NULL, NULL, NULL, '"2026-09-21T22:36:52.060Z"', '"2026-09-21T22:36:52.060Z"') ON CONFLICT (id) DO NOTHING;
INSERT INTO transactions (id, user_id, user_name, user_email, company_name, nif, plan_id, plan_name, amount_kz, currency, queries_granted, validity_days, payment_method, payment_reference, emis_reference, emis_terminal, payment_proof_name, payment_proof_url, payment_proof_size, gateway_fee_kz, net_amount_kz, notes, status, rejection_reason, reviewed_by_admin_id, reviewed_by_admin_name, reviewed_at, approved_at, created_at, updated_at) VALUES ('tx_pay_002', 'cli_002', 'Dra. Maria Eunice Santos', 'maria.santos@santosconsultoria.co.ao', 'Santos & Associados Consultoria', '5409281742', 'plan_platinum', 'Plano Platina Business (100 Consultas)', '5000.00', 'AOA', 100, 30, 'express_ref', 'MCX-REF-89421893', NULL, NULL, 'Talao_Multicaixa_Express_5000Kz.jpg', NULL, NULL, '0.00', '0.00', 'Pagamento efetuado no ATM Multicaixa Express.', 'pending', NULL, NULL, NULL, NULL, NULL, '"2026-09-21T22:36:52.060Z"', '"2026-09-21T22:36:52.060Z"') ON CONFLICT (id) DO NOTHING;
INSERT INTO transactions (id, user_id, user_name, user_email, company_name, nif, plan_id, plan_name, amount_kz, currency, queries_granted, validity_days, payment_method, payment_reference, emis_reference, emis_terminal, payment_proof_name, payment_proof_url, payment_proof_size, gateway_fee_kz, net_amount_kz, notes, status, rejection_reason, reviewed_by_admin_id, reviewed_by_admin_name, reviewed_at, approved_at, created_at, updated_at) VALUES ('tx_pay_003', 'cli_003', 'Eng. Carlos Alberto Mendes', 'carlos.mendes@mendesimport.ao', 'Mendes Import & Export Transitários', '5418829103', 'plan_silver', 'Plano Prata (30 Consultas)', '1500.00', 'AOA', 30, 30, 'bank_transfer', 'BFA-TRANSF-110293', NULL, NULL, 'Talao_BFA_1500Kz.pdf', NULL, NULL, '0.00', '0.00', 'Transferência interbancária validada.', 'approved', NULL, NULL, NULL, NULL, NULL, '"2026-09-21T22:36:52.060Z"', '"2026-09-21T22:36:52.060Z"') ON CONFLICT (id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- AUDIT LOGS TABLE DUMP
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- SUPPORT TICKETS TABLE DUMP
-- ----------------------------------------------------------------------------

COMMIT;
-- END OF DUMP